linters:
  enable-all: true
  disable:
    - funlen
    - wsl
    - wrapcheck
    - goerr113
    - nestif
    - exhaustivestruct
    - errorlint
linters-settings:
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 60
issues:
  exclude-rules:
    - text: "TLS InsecureSkipVerify set true"
      linters:
        - gosec
