language: go

go:
  - 1.x

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1

script:
  - go test -v ./...
  - golangci-lint run

before_deploy:
  - export REPO_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f2)
  - go build -o ${REPO_NAME}_${TRAVIS_TAG}
  - tar -czvf ${REPO_NAME}_${TRAVIS_TAG}_linux_amd64.tar.gz ${REPO_NAME}_${TRAVIS_TAG}
deploy:
  provider: releases
  api_key:
    secure: "vgnWMtme/KwK2XX2FZP99IS9yCAHl3Fg8AKZ9PSJc2vRN24oME1OCbIpwmIINYVSFxRCnXE3DyjDJcTY93GCvekqCpk5YEvIKJMLA9H47+iHLbezegSfTHstYrShb0tqsVD6B8bAuvs/rzTvjUiuAa8NRAhzNCk5FfKvYPc6L28af07GFoedwygda3IsUf7SuGywYxzuriihA6iqUvoaF2Iy/yCUEpJXYKVzrvlecF8szL3t4hhLaSbY4D5vGmdI5SoduCjseMhlYbdtEeW95TQZD5X65L47yqO7PfdqmEXML4vG/aeah8HwtyVlxKcBUdFZqof4uLFjiRHRJ1NDI2PcVIy4497QHVXL1hKRc5xuvBqctjcRuHBvoy11x5cPfUOZOX1in1VoA0as+LuhEU2x1jXL4CQ4TzOwuOJq3Q6B3BhdfytcfWMWxqvbIf/PMue9MzWGpynG4OuJ8HE58m5xbTwBPiohWvGz6eWKxlujni1Cgn3Ejye9/kbc1y/wasA4qfajUnCy10VFd+4mu5/zAAay4yrvSZTCIsDxUDKO95qrSYo2FGQbV7ZZm9W3wFcKbiGbHPBxpHYl0IsMK5AOReYDuVt4ujw6T+SwmdyxNYe7fjcN7E47XqDP1xb1Mgv1drBN8Rlz9u5Ddd5lf5QTsZabUcbTzyZy/mIy8LQ="
  file: ${REPO_NAME}_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
